# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [15]:
import numpy as np
print(np.__version__)

1.15.4


#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆)


In [19]:
print(np.zeros(19).itemsize)
print(np.zeros(19).size)

8
19


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [20]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [21]:
np_arr = np.zeros(10)
np_arr[4]=1
print(np_arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [23]:
arr=np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [30]:
arr=np.arange(1,5)
print(arr)
arr=arr[::-1]
print(arr)

[1 2 3 4]
[4 3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [28]:
mat=np.arange(0,9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [42]:
arr = np.array([1,2,0,0,4,0])
nonzero = np.nonzero(arr)
print(nonzero, arr[nonzero])

(array([0, 1, 4]),) [1 2 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [43]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [47]:
np.random.random((3,3))

array([[0.5214408 , 0.58422018, 0.75847024],
       [0.88090452, 0.97230949, 0.77609752],
       [0.97835886, 0.56079961, 0.68245458]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [50]:
mat=np.random.random((10,10))
#print(mat)
print(np.min(mat))
print(np.max(mat))

[[0.63030269 0.29526449 0.8832584  0.91232761 0.74313661 0.58184504
  0.16065045 0.36194702 0.09011931 0.2746833 ]
 [0.15094833 0.62201868 0.73334873 0.13094366 0.92647701 0.02916536
  0.62415806 0.15801483 0.31144703 0.02877351]
 [0.46046356 0.25402962 0.06810737 0.98046696 0.93135333 0.09138634
  0.19663109 0.4205799  0.91033383 0.46637254]
 [0.43631007 0.8314314  0.12341211 0.47113212 0.78024952 0.53296126
  0.85351793 0.71513284 0.50153249 0.52636231]
 [0.79404019 0.70932316 0.83550281 0.86198405 0.86152836 0.93547213
  0.46442241 0.39356468 0.3570804  0.8898516 ]
 [0.31672447 0.51039768 0.40307894 0.37536464 0.50550756 0.20073837
  0.3651456  0.41606325 0.60399075 0.92486115]
 [0.49395836 0.38400749 0.92615522 0.42665986 0.63736645 0.96132859
  0.21114076 0.15058112 0.20847533 0.32396332]
 [0.85449095 0.44507429 0.93964436 0.46234644 0.63214637 0.91539694
  0.86910348 0.12443754 0.28765585 0.37767191]
 [0.33748847 0.42352163 0.4568874  0.97113692 0.66258743 0.57001218
  0.1870163 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [3]:
np.random.random(30).mean()

0.5095267223730526

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [17]:
Z = np.ones((10,10))
print("Z before(1): \n", Z)
Z[1:-1] = 0
print("Z before(2): \n", Z)
Z[1:-1,1:-1] = 0
print("Z after: \n", Z)

Z before(1): 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Z before(2): 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Z after: 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [22]:
arr = np.arange(0,10)
padded = np.pad(arr,pad_width=1,mode='constant')
padded

array([0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [8]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3*0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [32]:
mat=np.arange(1,26).reshape(5,5)
print(mat)
print((np.diag(mat,k=-1)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 6 12 18 24]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [40]:
zeros=np.zeros((8,8))
zeros[::2,1::2]=1
zeros[1::2,::2]=1
zeros

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [46]:
mat=np.arange(0,6*7*8).reshape(6,7,8)
loc=np.where(mat==100)
print(loc)
print(np.unravel_index(100,(6,7,8)))

(array([1]), array([5]), array([4]))
(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [51]:
print(np.datetime64('today','D')- np.timedelta64(1,'D'))
print(np.datetime64('today','D'))
print(np.datetime64('today','D')+np.timedelta64(1,'W'))

2019-05-11
2019-05-12
2019-05-19


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [64]:
start=np.datetime64('2016-07-01')
vec=start+np.arange(31)
print(vec)

np.arange('2016-07','2016-08',dtype='datetime64[D]')

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [87]:
A=np.arange(1,4)
A =A.astype(float) #alternative np.arange(1,4, dtype=float)
print(A)
B=np.ones(3)
print(B)
C = A + B
D = C*(-A/2)
print("out: ", D)
np.add(A,B,out=B)
print(B)
np.multiply(-1.0,A,out=A)
print(A)
np.true_divide(A,2,out=A)
print(A)
np.multiply(A,B,out=A)
print("out2: ", A)

[1. 2. 3.]
[1. 1. 1.]
out:  [-1. -3. -6.]
[2. 3. 4.]
[-1. -2. -3.]
[-0.5 -1.  -1.5]
out2:  [-1. -3. -6.]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [107]:
A = np.arange(1,10,dtype=np.float)*np.random.random()*100
print("Orig:", A)
print(A.astype(int))
print(np.trunc(A))
print(np.floor(A))
print(np.ceil(A)-1)
print(A%1)
print(A-A%1)

Orig: [ 89.95353547 179.90707094 269.86060641 359.81414188 449.76767735
 539.72121282 629.67474828 719.62828375 809.58181922]
[ 89 179 269 359 449 539 629 719 809]
[ 89. 179. 269. 359. 449. 539. 629. 719. 809.]
[ 89. 179. 269. 359. 449. 539. 629. 719. 809.]
[ 89. 179. 269. 359. 449. 539. 629. 719. 809.]
[0.95353547 0.90707094 0.86060641 0.81414188 0.76767735 0.72121282
 0.67474828 0.62828375 0.58181922]
[ 89. 179. 269. 359. 449. 539. 629. 719. 809.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [109]:
np.ones((5,5))*np.arange(0,5)


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [114]:
arr = np.linspace(0,1,num=11,endpoint=False)[1:]
arr

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [112]:
np.info(np.linspace)

 linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

Parameters
----------
start : scalar
    The starting value of the sequence.
stop : scalar
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.
num : int, optional
    Number of samples to generate. Default is 50. Must be non-negative.
endpoint : bool, optional
    If True, `stop` is the last sample. Otherwise, it is not included.
    Default is True.
retstep : bool, optional
    If True, return (`samples`, `step`), where `step` is the spacing
    between samples.
dtype : dtype, optional
    The type of the ou

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [126]:
arr=np.random.random(10)
arr.sort()
print(arr)

[0.31751858 0.34392938 0.35008532 0.35310961 0.43502303 0.52671463
 0.61204883 0.66125816 0.90547743 0.96474947]


#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [131]:
A=np.random.randint(1,10,5)
B=np.random.randint(1,10,5)
print(A==B)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

[False False False False  True]
False
False


#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [13]:
arr=np.random.random(10)
print('arr: ', arr, ' len: ', len(arr))
print('arr max: ', np.max(arr))
arr[np.where(arr==np.max(arr))]=0
print('arr: ', arr)
arr2=np.random.random(10)
print('arr2: ', arr2, 'len: ', len(arr2))
m2=arr2.argmax()
print('arr2.argmax(): ', m2)
arr2[m2]=0
print('arr2: ', len(arr2))

arr:  [0.5118514  0.32546819 0.23093577 0.96129674 0.96163673 0.59169823
 0.45496925 0.08738475 0.85563955 0.13471836]  len:  10
arr max:  0.9616367319228133
arr:  [0.5118514  0.32546819 0.23093577 0.96129674 0.         0.59169823
 0.45496925 0.08738475 0.85563955 0.13471836]
arr2:  [0.19846118 0.32218973 0.17127116 0.02476323 0.64753781 0.17390592
 0.72202626 0.59107239 0.79827775 0.08621739] len:  10
arr2.argmax():  8
arr2:  10


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [16]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [45]:
Z=np.random.randint(1,50,size=10)
print(Z)
min_check=np.random.randint(1,50)
print(min_check)
X=np.abs(Z-min_check)
print(X)
print(Z[X.argmin()])

[24 14  1 28 39 47 13 17  2 26]
28
[ 4 14 27  0 11 19 15 11 26  2]
28


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [10]:
Z=np.random.randint(1,10,(3,3))
print(Z)
np.mean()
Z-np.mean(Z,axis=1)

[[5 5 7]
 [2 7 7]
 [9 2 4]]


array([[-0.66666667, -0.33333333,  2.        ],
       [-3.66666667,  1.66666667,  2.        ],
       [ 3.33333333, -3.33333333, -1.        ]])

#### 59. How to sort an array by the nth column? (★★☆)

In [29]:
Z=np.random.randint(1,10,(3,3))
print('orig:' , Z)
print('row modified(2,0,1): ',Z[[2,0,1]])
print('col modified(:,1,2,0): ', Z[:,[1,2,0]])
#print(Z[:,1].argsort())
print('sorted: ', Z[Z[:,1].argsort()])

orig: [[4 6 8]
 [7 8 3]
 [5 7 1]]
row modified(2,0,1):  [[5 7 1]
 [4 6 8]
 [7 8 3]]
col modified(:,1,2,0):  [[6 8 4]
 [8 3 7]
 [7 1 5]]
sorted:  [[4 6 8]
 [5 7 1]
 [7 8 3]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

In [54]:
Z=np.random.randint(1,10,(10))
print('ARR: ', Z)
rand = np.random.randint(1,10)
print('RAND VAL: ', rand)
print('FIRST LOCATION: ', np.absolute(Z-rand).argmin())
print('ALL LOCATION: ', np.unravel_index(np.absolute(Z-rand).argmin(),Z.shape))
print('VALUE: ', Z[np.absolute(Z-rand).argmin()])

ARR:  [1 9 1 2 4 2 7 2 6 8]
RAND VAL:  2
FIRST LOCATION:  3
ALL LOCATION:  (3,)
VALUE:  2


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [58]:
X=np.random.randint(1,50,(1,3))
Y=np.random.randint(1,50,(3,1))
Z=X+Y
print(X,"\n",Y,"\n",Z)

[[25 34 26]] 
 [[24]
 [48]
 [49]] 
 [[49 58 50]
 [73 82 74]
 [74 83 75]]


#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)